# Generated by Django 2.0.13 on 2021-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_auto_20210513_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_criminal',
            field=models.NullBooleanField(),
        ),
    ]
