# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - SFapp(Production), Build and deploy Python app

on:
  push:
    branches:		
    - develop		
  pull_request:		
    branches:	
    - develop

env:
  WORKING_DIRECTORY: '.'
  PYTHON_VERSION: '3.8'
  STARTUP_COMMAND: '' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        sudo apt install python${{ env.PYTHON_VERSION }}-venv
        python -m venv --copies antenv
        source antenv/bin/activate
        pip install setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install django-pyodbc-azure 
        pip install azure-cognitiveservices-vision-face
        pip install matplotlib
        
    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: SFapp
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_23A6D047141946629713AF22B4C3C4FE }}
        package: ${{ env.WORKING_DIRECTORY }}
        startup-command: ${{ env.STARTUP_COMMAND }}

