# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t docker.pkg.github.com/Polina-Lelis/SFProject/SafeFace:${{ github.sha }}
        docker push docker.pkg.github.com/Polina-Lelis/SFProject/SafeFace:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'SafeFace'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'docker.pkg.github.com/Polina-Lelis/SFProject/SafeFace:${{ github.sha }}'
